{{- if .Values.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name | default (include "theia-rodrigo.fullname" .) }}
  labels:
    {{- include "theia-rodrigo.labels" . | nindent 4 }}
{{- with .Values.configMap.data }}
data:
 {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}